name: On merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - README.md
      - .github/**
      - .*

permissions:
  contents: write

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create new tag
        run: |
            LAST_TAG=$(git tag --sort=creatordate --sort=v:refname | tail -n1)
            NEW_TAG=$(echo "$LAST_TAG" | awk '{split(substr($0, 2), a, "."); printf "v%d.%d.%d", a[1], a[2], a[3]+1}')
            git tag $NEW_TAG
            git push --tags
